app_news/urls.py
from django.urls import path

from .views import (
    AddNewsView,
    ListNewsView,
    DetailNewsView, 
    NewsUpdateView, 
    NewsDeleteView,
    SendEmailView,
    SendEmailsView,
)

urlpatterns = [
    path('add/', AddNewsView.as_view(), name='add_news'),
    path('<int:pk>/', DetailNewsView.as_view(), name='show_news'),
    path('', ListNewsView.as_view(), name='list_news'),
    path('edit/<int:pk>/', NewsUpdateView.as_view(), name='update_news'),
    path('delete/<int:pk>/', NewsDeleteView.as_view(), name='delete_news'),
    path('send/', SendEmailView.as_view(), name='send_email'),
    path('send_mails/', SendEmailsView.as_view(), name='send_emails')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('news/', include('app_news.urls')),
    path('', TemplateView.as_view(template_name='base.html'), name='home')
]

app_news/models.py
from django.contrib.auth import get_user_model
from django.db import models


# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=255)

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name_plural = "Categories"
        db_table = 'categories'


class News(models.Model):
    news_title = models.CharField(max_length=255, unique=True)
    news_description = models.CharField(max_length=255)
    news_image = models.ImageField(upload_to='news/')
    news_content = models.TextField()
    news_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    news_pub_date = models.DateTimeField(auto_now_add=True)
    news_author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.news_title

    class Meta:
        verbose_name_plural = "News"
        db_table = 'news'

app_news/views.py
from email import message

from django.conf.global_settings import EMAIL_HOST_USER
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.core import send_mail
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView,View
from django.views.generic.edit import UpdateView, DeleteView



from app_news.models import News


# Create your views here.
class AddNewsView(LoginRequiredMixin, CreateView):
    template_name = 'news/add_news.html'
    model = News
    success_url = reverse_lazy('home')
    fields = ['news_title', 'news_description', 'news_image', 'news_content', 'news_category']
    
    def form_valid(self, form):
        form.instance.news_author = self.request.user
        return super().form_valid(form)


class ListNewsView(ListView):
    template_name = 'news/list_news.html'
    model = News
    paginate_by = 2
    # context_object_name = 'xabar'


class DetailNewsView(DetailView):
    template_name = 'news/show_news.html'
    model = News





class NewsUpdateView(LoginRequiredMixin, UpdateView):
    model = News
    fields = ['news_title', 'news_description', 'news_image', 'news_content', 'news_category'] 
    template_name = 'news/update_news.html'
    success_url = reverse_lazy('home')

class NewsDeleteView(LoginRequiredMixin, DeleteView):
    model = News
    template_name = 'news/delete_news.html'  # HTML-malumotlar manbani nomi
    success_url = reverse_lazy('home')  # O'chirish muvaffaqiyatli amalga oshirildiqdan keyin qayerga qaytish kerakligi


class SuperuserRequiredMixin (UserPassesTestMixin):
    def __init__(self):
        self.request = None

    def test_func(self):
        return self.request.user.is_superuser


class SendEmailView(SuperuserRequiredMixin, LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        return render(request, template_name='news/send_email.html')

def post(self, request, *args, **kwargs):
    subject = request.POST.get('subject')
    message=request.POST.get('message')

    users=User.objects.all()
    for user in users:
        recipient_list = [user.email]
        send_mail(subject, message, EMAIL_HOST_USER, recipient_list)
        return render(request, template_name='news/send_email.html')

 
class SendEmailsView(View):

    def get(self, request, *args, **kwargs):
        return render(request, template_name='news/send_emails.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        	Django auth
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Logo</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">News</a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'list_news' %}">All news</a></li>
                  <hr>
                <li><a class="dropdown-item" href="{% url 'add_news' %}">Add news</a></li>
                <li><a class="dropdown-item" href="{% url 'send_email' %}">Send mail</a></li>
{#                <li><a class="dropdown-item" href="{% url 'delete_news' %}">Delete news</a></li>#}
                <li><a class="dropdown-item" href="#">A third link</a></li>
              </ul>
            </li>
      </ul>
    </div>
  </div>
</nav>
   
    {% block content %}
    	
    {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/news/add_news.html
{% extends 'base.html' %}

{% block title %}
	Add news
{% endblock %}

{% block content %}
	<h1>Add news</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Insert news" class="btn btn-success">
    </form>
{% endblock %}

templates/news/delete_news.html
{% extends 'base.html' %}

{% block title %}
	Delete news
{% endblock %}

templates/news/list_news.html
{% extends 'base.html' %}

{% block title %}
	List news
{% endblock %}

{% block content %}
	<h1>List news</h1>
    {% for news in news_list %}
    	<p>
            <a href="{% url 'show_news' news.pk %}">{{ news.news_title }}</a>
        </p>
    {% endfor %}

    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="{% url 'list_news' %}?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}

        {% for page in paginator %}
            {% if page.number == page_obj.number %}
                <li class="page-item"><a class="page-link disabled" disabled>{{ page.number }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="{% url 'list_news' %}?page={{ page.number }}">{{ page.number }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="{% url 'list_news' %}?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>

{% endblock %}

templates/news/send_email.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Superuser Sahifasi</title>
</head>
<body>
<div class="container">
    <h1>Superuser Sahifasi</h1>
    <form action="send_emails.html" method="POST">
        <label for="fullname">To'liq ismingiz:</label><br>
        <input type="text" id="fullname" name="fullname" required><br><br>
        <label for="email">Email manzilingiz:</label><br>
        <input type="email" id="email" name="email" required><br><br>
        <label for="message">Xabaringiz:</label><br>
        <textarea id="message" name="message" rows="4" required></textarea><br><br>
        <button type="submit">Jo'natish</button>
    </form>
</div>
</body>
</html>

templates/news/send_emails.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Xabarnoma</title>
</head>
<body>

</body>
</html>

templates/news/show_news.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
	{{ news.news_title }}
{% endblock %}

{% block content %}
	<h1>{{ news.news_title }}</h1>
    <img src="{% static news.news_image %}" alt="" width="400" style="float:right;">
    <p>
        {{ news.news_content }}
    </p>
    <p>Author: {{ news.news_author }}</p>
    {% if user.is_authenticated %}
        <p>
            <a href="{% url 'update_news' news.pk %}" class="btn btn-succes"> UPDATE </a>
            <a href="{% url 'delete_news' news.pk %}" class="btn btn-succes"> DELETE </a>
        </p>
        
    {% endif %}
{% endblock %}

templates/news/update_news.html
{% extends 'base.html' %}

{% block title %}
	Edit news
{% endblock %}

{% block content %}
	<h1>Edit news</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save changes" class="btn btn-success">
    </form>
{% endblock %}